services:
    hookd:
        container_name: hookd
        image: joebobmiles/hookd
        restart: unless-stopped
        ports:
            - "${HOOKD_HOST_PORT:-6578}:${HOOKD_PORT:-6578}"
        volumes:
            - ./src/scripts:/tmp/scripts