services:
    hookd:
        container_name: hookd
        image: ghcr.io/joebobmiles/hookd
        restart: unless-stopped
        ports:
            - "${HOOKD_HOST_PORT:-6578}:${HOOKD_PORT:-6578}"
        volumes:
            - ./src/scripts:/tmp/scripts
            - /var/run/docker.sock:/var/run/docker.sock
        privileged: yes